Algorithm1 wordfreq update
Dorffasaurus/quorum-language-cs472 pull request #16
Opened 2023-11-24 23:40 UTC by ProjectZuki

## Additions
Added functionality to word frequency.quorum to initialize hash table of stop words on initialization of WordFrequency.
Optional function added to remove stopwords from WordFrequency.

## Changes
Function Calculate() has been changed to Calculate_from_file() because there will be another method to calculate from a text giving us both options.

2023-11-24 23:47 UTC, Dorffasaurus commented on WordCountAlgo/wizard_of_oz.txt
Please remove this

2023-11-24 23:48 UTC, Dorffasaurus commented on WordCountAlgo/Main.quorum
remove the main.quorum file

2023-11-24 23:49 UTC, ProjectZuki commented on WordCountAlgo/wizard_of_oz.txt
removed wizard_of_oz.txt

2023-11-24 23:49 UTC, ProjectZuki commented on WordCountAlgo/Main.quorum
removed main.quorum

2023-11-24 23:56 UTC, Dorffasaurus requested changes

2023-11-24 23:56 UTC, Dorffasaurus commented on WordCountAlgo/WordFrequency.quorum
> +        stopwordsreader:OpenForRead(stopwordsfile)
instead of requiring a file on create can we use a getter and setter function to set the stopwords.

2023-11-24 23:56 UTC, Dorffasaurus commented on WordCountAlgo/WordFrequency.quorum
>          Iterator<text> wordMapItr = WordCountMap:GetKeyIterator()
can we add a class variable that tracks how many unique words have been added? Then we can get rid of this function and just add a getter to return it.

2023-11-27 07:20 UTC, ProjectZuki commented
Updated the contents of WordFrequency.quorum

### Changes
Modified SetFrequencyMap() to check if input text is filepath, if not will process as text (e.g. tweet, article)

Removed RemoveStopWords(), as SetFrequencyMap() will automatically remove them

Removed constructor, for same reason.

SetStopWords() requires filepath (text) for stopwords file

Modified GetTotalWords -> GetWordCount() to return total words.

2023-11-28 23:23 UTC, Dorffasaurus approved these changes
Thanks for your work, appreciate the changes.

2023-11-28 23:24 UTC, merged